name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # run from actions
  
env:
  BUILD_TYPE: Release # use as ${{env.BUILD_TYPE}}

jobs:
  windows-build:
    name: Windows Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Create build directory and run CMake
      shell: cmd
      # curl -L = redirect
      # curl -o = output
      # 7z x = extract
      # 7z -o = output
      # cmake -S = source dir
      # cmake -B = build dir
      # cmake -G = generator
      # cmake -A = architecture
      # cmake -D = defines 
      run: |
        mkdir cmake_download_dir
        set DOWNLOAD_FILE_BOOST=boost_1_72_0.zip
        set DOWNLOAD_ADDRESS_BOOST=https://sourceforge.net/projects/boost/files/boost/1.72.0/boost_1_72_0.zip/download
        echo download file %DOWNLOAD_FILE_BOOST% from address %DOWNLOAD_ADDRESS_BOOST%
        curl -L -o %DOWNLOAD_FILE_BOOST% %DOWNLOAD_ADDRESS_BOOST%
        7z x %DOWNLOAD_FILE_BOOST% -ocmake_download_dir
        cmake -S . -B cmake_build_dir -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=cmake_install_dir -DBOOST_ROOT=cmake_download_dir/boost_1_72_0
    - name: Build project
      run: cmake --build cmake_build_dir --target INSTALL --config Release -- /nologo /verbosity:minimal /maxcpucount:2 /property:MultiProcessorCompilation=true
    - name: Create Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Windows-Artifacts
        path: cmake_install_dir/
      if: always()
